
a = "Send all BTC in address to recipient's address"
c = "Change address"
f = "mining fee"
p = "Send some of BTC in address to recipient's address and balance to change address"
q = "The ammount of BTC being sent to recipient's address in SATs"
r = "The address you are sending BTC to"
s = "Your cloud HSM's private key(SK) handle"
v = "Your cloud HSM's public key(VK) handle"
out = "Path where you want altpiggybank to write file"
